# fly.toml file generated for bigmacro-server on 2024-01-02T02:47:10-05:00

app = "bigmacro-server"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bos"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
